version: "3.9"
services:
  fraud-api:
    command: npm run dev
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    environment:
      NODE_ENV: development

  fraud-worker:
    command: npm run dev
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    environment:
      NODE_ENV: development
