---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: molam-id-pdb
  namespace: molam
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: molam-id
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: molam-notifications-api-pdb
  namespace: molam
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: molam-notifications-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: molam-translation-api-pdb
  namespace: molam
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: molam-translation-api
